spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flashtix_db?useSSL=false&serverTimezone=UTC
    username: root
    password: networksecure@56 # Replace with your MySQL password
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates tables
    show-sql: true # Helps debug by showing SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: flashtix-ticketing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

minio:
  url: http://localhost:9000
  access-key: admin # Use your actual MinIO key
  secret-key: password123 # Use your actual MinIO key
  bucket-name: flashtix-assets #
  #cdn-domain: http://localhost:9000